#!/bin/bash
#SBATCH --ntasks-per-node=16
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=2
#SBATCH --time=800:00:00
#SBATCH --mincpus=32
#SBATCH --mem-per-cpu=1000
##SBATCH --exclude=atmnode001,atmnode002,atmnode003,atmnode004,atmnode005,atmnode006,atmnode011,atmnode012,atmnode013,atmnode014,atmnode017,atmnode018,atmnode019,atmnode020,atmnode021,atmnode022,atmnode023,atmnode024,atmnode025,atmnode026
##SBATCH --nodelist=atmnode010
#SBATCH --output=grey_titan_r10_res.out
#SBATCH -p priority-rp
source $HOME/.bashrc
cd $HOME/research/isca_dir/Isca/exp/grey_suprot_test/gcm_test/titan_gcm_test_new/
$HOME/anaconda3/envs/isca_env2/bin/python grey_titan_r10_res.py
