#!/bin/bash
#SBATCH --ntasks-per-node=32
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=2
#SBATCH --time=800:00:00
#SBATCH --mincpus=64
#SBATCH --mem-per-cpu=1000
##SBATCH --exclude=atmnode007,atmnode008,atmnode009,atmnode010,atmnode011,atmnode012,atmnode013,atmnode014,atmnode015,atmnode016,atmnode025,atmnode026,atmnode027,atmnode028
#SBATCH --nodelist=atmnode023
#SBATCH --output=venus_hs_daily_inst.out
#SBATCH -p priority-rp
source $HOME/.bashrc
cd $HOME/research/isca_dir/Isca/exp/venus_hs/
$HOME/anaconda3/envs/isca_env/bin/python venus_test_daily.py
