#!/bin/bash
#SBATCH --ntasks-per-node=24
#SBATCH --ntasks=24
#SBATCH --cpus-per-task=2
#SBATCH --time=800:00:00
#SBATCH --mincpus=24
##SBATCH --exclude=atmnode007,atmnode008,atmnode009,atmnode010,atmnode011,atmnode012,atmnode013,atmnode014,atmnode015,atmnode016,atmnode025,atmnode026,atmnode027,atmnode028
#SBATCH --nodelist=atmnode010
#SBATCH --output=grey_tl_60_TJ001.out
##SBATCH -p priority-rp
source $HOME/.bashrc
cd $HOME/research/isca_dir/Isca/exp/grey_suprot_diurnal/
$HOME/anaconda3/envs/isca_env2/bin/python grey_tl_TJ.py
